motzi:
  name: Motzi Bread
  short_name: Motzi
  marketing_domain: motzibread.com
  app_domain: motzibread.herokuapp.com
  email_reply_to: motzi.bread@gmail.com
  pay_it_forward: true
  pay_what_you_can: true
  js_tracking: true
